name: Hello Testing

on:
  push:
    branches:
    - release/*
jobs:
  build-and-run:
    name: Build and Run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build Code
        run: pwd && whoami && ls -l && make && ls -l
      - name: Nominal Run
        run: ./hello
