name: Hello Testing

on: [push]

jobs:
  build-and-run:
    name: Build and Run
    runs-on: ubuntu-latest
    steps:
      - use: actions/checkout@v1
      - name: Build Code
        run: pwd && whoami && ls -l && make
      - name: Nominal Run
        run: ./hello
