name: Hello Testing

on:
  push:
    branches:
      - release
jobs:
  build-and-run:
    name: Build and Run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          ref: refs/heads/release
      - name: Build Code
        run: git branch && make && ls -l
      - name: Nominal Run
        run: ./hello
